apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "prompt"
  namespace: "argocd"
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "!kube-system"
      server: "*"
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
