apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "prompt-proto-service.fullname" . }}-secret
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/{{ template "prompt-proto-service.fullname" . }}"
  type: Opaque
