{{- $root := . -}}
{{- $applist := splitList "@" .Values.global.enabledServices }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-generated-config
data:
  telegraf-generated.conf: |+
      [global_tags]
        cluster = {{- .Values.global.host | quote }}
      [agent]
        hostname = "telegraf-$HOSTIP"
        interval = "120s"
        flush_interval = "120s"
        collection_jitter = "10s"
        metric_batch_size = 10000
        metric_buffer_limit = 100000

      [[inputs.kubernetes]]
        url = "https://$HOSTIP:10250"
        bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify = true
        namepass = ["kubernetes_pod_container"]
        fieldinclude = ["cpu_usage_nanocores", "memory_usage_bytes"]

      [[inputs.kube_inventory]]
        url = "https://kubernetes.default.svc"
        bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
        # Only worry about pods
        resource_exclude = [ "daemonsets", "deployments", "endpoints", "ingress", "nodes", "persistentvolumes", "persistentvolumeclaims", "services", "statefulsets" ]
        resource_include = [ "pods" ]
        insecure_skip_verify = true
        namespace = ""
  {{- if has "monitoring" $applist }}
      # We only care about host disk space and CPU
      # for the monitoring application.
      [[inputs.cpu]]
        percpu = true
        totalcpu = true
        collect_cpu_time = false
        report_active = false

      [[inputs.disk]]
        ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
  {{- end }}

  {{- range $app := $applist }}
    {{- if $app }}
      {{- $bucket := replace "-" "_" $app }}
      {{- $namespace := replace "_" "-" $app }}

      [[outputs.influxdb_v2]]
        urls = [{{- $root.Values.config.influxdb2Url | quote }}]
        token = "$INFLUX_TOKEN"
        organization = {{ $root.Values.config.influxdb2Org | quote }}
        bucket = {{ $bucket | quote }}
        [outputs.influxdb_v2.tagpass]
          namespace = [{{ $namespace | quote }}]
    {{- end }}
  {{- end }}
