apiVersion: v1
kind: Service
metadata:
  name: "gafaelfawr"
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: "http"
  selector:
    {{- include "gafaelfawr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "frontend"
  sessionAffinity: "None"
