image:
  pullPolicy: Always
ingress:
  defaultScope: "exec:admin"
config:
  logLevel: "DEBUG"
  databaseUrl: "postgresql://times-square@localhost/times-square"
  githubAppId: "952868"
  enableGitHubApp: "True"
cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-demo-9e05:us-central1:science-platform-demo-a4dbbf96"
  serviceAccount: "times-square@science-platform-demo-9e05.iam.gserviceaccount.com"
redis:
  persistence:
    storageClass: "standard-rwo"
