{{- if not .Values.secretsOnly }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: csc-env-config
data:
    LSST_SITE: {{ $.Values.global.controlSystem.siteTag }}
    LSST_TOPIC_SUBNAME: {{ $.Values.global.controlSystem.topicName }}
    LSST_KAFKA_BROKER_ADDR: {{ $.Values.global.controlSystem.kafkaBrokerAddress }}
    LSST_KAFKA_REPLICATION_FACTOR: {{ $.Values.global.controlSystem.kafkaTopicReplicationFactor | quote }}
    LSST_KAFKA_SECURITY_USERNAME: ts-salkafka
    LSST_SCHEMA_REGISTRY_URL: {{ $.Values.global.controlSystem.schemaRegistryUrl }}
    S3_ENDPOINT_URL: {{ $.Values.global.controlSystem.s3EndpointUrl }}
{{- end }}
