---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.global.controlSystem.appNamespace }}
spec:
  path: {{ .Values.global.vaultSecretsPath }}/{{ .Values.global.controlSystem.appNamespace }}
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: {{ $.Values.global.vaultSecretsPath }}/pull-secret
  type: kubernetes.io/dockerconfigjson
