cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfprod-sso"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-stable-6994:us-central1:science-platform-stable-0c29612b"
    serviceAccount: "ssotap@science-platform-stable-6994.iam.gserviceaccount.com"
    database: "ssotap"
