apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: <CHARTNAME>-db-worker
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
spec:
  podSelector:
    # This policy controls inbound access to the database workers.
    matchLabels:
      {{- include "<CHARTNAME>.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "db-worker"
  policyTypes:
    # Block all inbound access.
    - Ingress
