name: ccin2p3
fqdn: data-dev.lsst.eu
vaultPathPrefix: secret/phalanx/ccin2p3

applications:
  datalinker: true
  nublado: true
  portal: true
  postgres: true
  semaphore: true
  squareone: true
  tap: true
  mobu: false
