# Follow the example of plot-navigator

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: schedview-snapshot
  labels:
    {{- include "schedview-snapshot.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/schedview-snapshot"
  type: Opaque
