# Default values for squarebot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# Global parameters will be set by parameters injected by Argo CD and should
# not be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

# -- Number of API pods to run
replicaCount: 1

image:
  # -- Squarebot image repository
  repository: ghcr.io/lsst-sqre/sqrbot

  # -- Image pull policy
  pullPolicy: IfNotPresent

  # -- Tag of the image
  # @default -- The appVersion of the chart
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

# -- Annotations for API and worker pods
podAnnotations: {}

# -- Resource requests and limits for sqrbot-sr
# @default -- See `values.yaml`
resources:
  limits:
    cpu: "1"
    memory: "600Mi"
  requests:
    cpu: "4m"
    memory: "290Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  # -- Logging level: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  logLevel: "INFO"

  # -- Hubot username
  username: "sqrbot"

  # -- Jira base URL
  jiraUrl: "https://rubinobs.atlassian.net"
