{{- if .Values.configfile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}-configfile
  namespace: {{ $.Values.global.controlSystem.appNamespace }}
data:
  {{ .Values.configfile.filename }}:
{{ .Values.configfile.content | toYaml | indent 4 }}
{{- end }}

