config:
  influxdb2Url: "https://monitoring.lsst.cloud"
  influxdb2Org: "square"
telegraf-ds:
  args:
  - "--config"
  - "/etc/telegraf-generated/telegraf-generated.conf"
  env:
  # Token to communicate with Influx
  - name: INFLUX_TOKEN
    valueFrom:
      secretKeyRef:
        name: telegraf
        key: influx-token
  # This pulls HOSTNAME from the node, not the pod.
  - name: HOSTNAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  # In test clusters where hostnames are resolved in /etc/hosts on each node,
  # the HOSTNAME is not resolvable from inside containers
  # So inject the host IP as well
  - name: HOSTIP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  # Mount the host filesystem and set the appropriate env variables.
  # ref: https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md
  # HOST_PROC is required by the cpu, disk, diskio, kernel and processes input plugins
  - name: "HOST_PROC"
    value: "/hostfs/proc"
  # HOST_SYS is required by the diskio plugin
  - name: "HOST_SYS"
    value: "/hostfs/sys"
  - name: "HOST_MOUNT_PREFIX"
    value: "/hostfs"
  rbac:
    create: true
  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
    requests:
      memory: "350Mi"
      cpu: "50m"


  serviceAccount:
    name: telegraf-ds

  # Set to effectively empty and just use generated config instead.
  override_config:
    toml: |+
      [agent]
        logfile=""
  volumes:
  - name: telegraf-generated-config
    configMap:
      name: "telegraf-generated-config"
  mountPoints:
  - name: telegraf-generated-config
    mountPath: /etc/telegraf-generated

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- services enabled in this RSP instance
  # @default -- Set by Argo CD
  enabledServices: ""

  # -- Host name for instance identification
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
