ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    service:
      loadBalancerIP: "10.0.1.90"
    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate
vaultCertificate:
  enabled: true
