config:
  influxdbHostname: "monitoring.lsst.cloud"
  influxdbOrg: "square"
influxdb2:
  enabled: true
  ingress:
    enabled: true
    hostname: "monitoring.lsst.cloud"
  # -- Schedule onto the kafka pool
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "kafka"
    effect: "NoExecute"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "roundtable.lsst.cloud/pool"
            operator: "In"
            values:
            - "kafka"
chronograf:
  enabled: true
  ingress:
    enabled: true
    hostname: "roundtable.lsst.cloud"
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard-rwo
  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: "https://roundtable.lsst.cloud/auth/openid/login"
    GENERIC_TOKEN_URL: "https://roundtable.lsst.cloud/auth/openid/token"
    USE_ID_TOKEN: "1"
    JWKS_URL: "https://roundtable.lsst.cloud/.well-known/jwks.json"
    GENERIC_API_URL: "https://roundtable.lsst.cloud/auth/openid/userinfo"
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: "https://roundtable.lsst.cloud/"
    STATUS_FEED_URL: "https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/roundtable.json"
    INFLUX_DB_URL: "monitoring.lsst.cloud"
  envFromSecret: "monitoring"
cronjob:
  enabled: true
  debug: true
ingress:
  enabled: true
  influxdb2:
    hostname: "monitoring.lsst.cloud"
