apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fastapi-bootcamp"
  labels:
    {{- include "fastapi-bootcamp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fastapi-bootcamp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "fastapi-bootcamp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.config.slackAlerts }}
          env:
            - name: "FASTAPI_BOOTCAMP_SLACK_WEBHOOK_URL"
              valueFrom:
                secretKeyRef:
                  name: "fastapi-bootcamp-secret"
                  key: "slack-webhook"
          {{- end }}
          envFrom:
            - configMapRef:
                name: "fastapi-bootcamp"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/"
              port: "http"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: "tmp"
              mountPath: "/tmp"
            - name: "astropy-cache"
              mountPath: "/home/appuser/.astropy"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: "tmp"
          emptyDir: {}
        - name: "astropy-cache"
          emptydir: {}
