{{- if .Values.config.slackAlerts }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "fastapi-bootcamp-secret"
  labels:
    {{- include "fastapi-bootcamp.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/fastapi-bootcamp"
  type: "Opaque"
{{- end }}
