cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfprod-tap"

  config:
    qserv:
      host: "10.140.1.211:4040"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-stable-6994:us-central1:science-platform-stable-0c29612b"
    serviceAccount: "tap-service@science-platform-stable-6994.iam.gserviceaccount.com"
    database: "tap"
